name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more info?
      placeholder: example@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: dropdown
    id: has_bounty
    attributes:
      label: 💰 Is there a bounty for this issue?
      description: Select whether this task has a reward
      options:
        - "Yes"
        - "No"
        - "Not yet, but maybe later"
    validations:
      required: true

  - type: input
    id: bounty_amount
    attributes:
      label: 💵 Bounty Amount (if any)
      description: Enter a suggested or actual bounty amount
      placeholder: "$50 USD"
    validations:
      required: false

  - type: textarea
    id: bounty_description
    attributes:
      label: 📜 Bounty Details (if applicable)
      description: Add any rules, payout conditions, or links to Gitpay listings
      placeholder: |
        Example:
        - Paid via Gitpay once PR is merged and reviewed
        - Must include unit tests and follow code standards
        - Listing: https://gitpay.me/tasks/1234
    validations:
      required: false

