name: 📝 Custom Task
description: Create a custom task or operational issue for Gitpay contributors
title: "[Task] "
labels: ["task", "gitpay"]
body:
  - type: input
    id: title
    attributes:
      label: 🧩 Task Title
      placeholder: "Example: Refactor the Stripe webhook handler"
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: 📄 Task Description
      description: Explain what needs to be done, why, and any important context
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      placeholder: |
        - [ ] Code is tested
        - [ ] PR is linked to issue
        - [ ] Docs are updated
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: 🗂️ Files / Areas Affected
      placeholder: "Mention files, components, or features to touch"
    validations:
      required: false

  - type: dropdown
    id: ui_related
    attributes:
      label: 🎨 Does this involve UI work?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ Screenshot / Reference (if applicable)
      description: Add a screenshot or mockup if visual work is involved
      placeholder: "Paste an image or drag-and-drop here"
    validations:
      required: false

  - type: dropdown
    id: has_bounty
    attributes:
      label: 💰 Is there a bounty for this issue?
      description: Select whether this task has a reward
      options:
        - "Yes"
        - "No"
        - "Not yet, but maybe later"
    validations:
      required: true

  - type: input
    id: bounty_amount
    attributes:
      label: 💵 Bounty Amount (if any)
      description: Enter a suggested or actual bounty amount
      placeholder: "$50 USD"
    validations:
      required: false

  - type: textarea
    id: bounty_description
    attributes:
      label: 📜 Bounty Details (if applicable)
      description: Add any rules, payout conditions, or links to Gitpay listings
      placeholder: |
        Example:
        - Paid via Gitpay once PR is merged and reviewed
        - Must include unit tests and follow code standards
        - Listing: https://gitpay.me/tasks/1234
    validations:
      required: false

