name: 🎨 UI Issue
description: Report a problem or request related to the user interface
title: "[UI] "
labels: ["ui", "gitpay", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: ✏️ Summary
      placeholder: "Example: Button misaligned on mobile"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      placeholder: "Describe the visual issue or component behavior"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Steps to Reproduce
      placeholder: |
        1. Go to home page
        2. Resize to mobile
        3. Observe button shift
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Result
      placeholder: "Button should remain centered in mobile view"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ Screenshot / Mockup
      placeholder: "Paste image or drag and drop here"
    validations:
      required: true

  - type: input
    id: tech
    attributes:
      label: 🧰 UI Stack Used
      placeholder: "React, Tailwind, AntD, Styled-components..."
    validations:
      required: false

  - type: dropdown
    id: has_bounty
    attributes:
      label: 💰 Is there a bounty for this issue?
      description: Select whether this task has a reward
      options:
        - "Yes"
        - "No"
        - "Not yet, but maybe later"
    validations:
      required: true

  - type: input
    id: bounty_amount
    attributes:
      label: 💵 Bounty Amount (if any)
      description: Enter a suggested or actual bounty amount
      placeholder: "$50 USD"
    validations:
      required: false

  - type: textarea
    id: bounty_description
    attributes:
      label: 📜 Bounty Details (if applicable)
      description: Add any rules, payout conditions, or links to Gitpay listings
      placeholder: |
        Example:
        - Paid via Gitpay once PR is merged and reviewed
        - Must include unit tests and follow code standards
        - Listing: https://gitpay.me/tasks/1234
    validations:
      required: false

