name: 🧠 Backend Issue
description: Report a backend issue related to APIs, DB, logic, or services
title: "[BE] "
labels: ["backend", "gitpay", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: ✏️ Summary
      placeholder: "Example: Payment webhook not storing payout logs"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      placeholder: "Describe the issue or enhancement needed in backend"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Steps to Reproduce (or trigger)
      placeholder: |
        1. Trigger webhook manually
        2. Observe logs
        3. No record found in DB
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      placeholder: "Webhook should log all payout transactions"
    validations:
      required: true

  - type: input
    id: stack
    attributes:
      label: 🛠️ Stack Affected
      placeholder: "Node.js, PostgreSQL, Stripe SDK, Sequelize..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📜 Relevant Logs / Payload
      description: Share any logs, error messages, or example payloads
      render: shell
    validations:
      required: false

 - type: dropdown
    id: has_bounty
    attributes:
      label: 💰 Is there a bounty for this issue?
      description: Select whether this task has a reward
      options:
        - "Yes"
        - "No"
        - "Not yet, but maybe later"
    validations:
      required: true

  - type: input
    id: bounty_amount
    attributes:
      label: 💵 Bounty Amount (if any)
      description: Enter a suggested or actual bounty amount
      placeholder: "$50 USD"
    validations:
      required: false

  - type: textarea
    id: bounty_description
    attributes:
      label: 📜 Bounty Details (if applicable)
      description: Add any rules, payout conditions, or links to Gitpay listings
      placeholder: |
        Example:
        - Paid via Gitpay once PR is merged and reviewed
        - Must include unit tests and follow code standards
        - Listing: https://gitpay.me/tasks/1234
    validations:
      required: false

