name: 🧠 Backend Issue
description: Report a backend issue related to APIs, DB, logic, or services
title: "[BE] "
labels: ["backend", "gitpay", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: ✏️ Summary
      placeholder: "Example: Payment webhook not storing payout logs"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      placeholder: "Describe the issue or enhancement needed in backend"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Steps to Reproduce (or trigger)
      placeholder: |
        1. Trigger webhook manually
        2. Observe logs
        3. No record found in DB
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      placeholder: "Webhook should log all payout transactions"
    validations:
      required: true

  - type: input
    id: stack
    attributes:
      label: 🛠️ Stack Affected
      placeholder: "Node.js, PostgreSQL, Stripe SDK, Sequelize..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📜 Relevant Logs / Payload
      description: Share any logs, error messages, or example payloads
      render: shell
    validations:
      required: false

  - type: input
    id: bounty
    attributes:
      label: 💰 Suggested Bounty (Optional)
      placeholder: "$60 USD"
    validations:
      required: false
