blank_issues_enabled: false
contact_links:
  - name: Gitpay Discussions
    url: https://github.com/worknenjoy/gitpay/discussions
    about: Please ask and answer questions here.
  - name: Gipay website
    url: https://gitpay.me
    about: See the platform in production
